apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 80
      - path: /http
        backend: 
          serviceName: httpd
          servicePort: 80

